name: code format for rust

on:
  push:
    files:
      - '**/*.rs'

jobs:
  format:
    runs-on: ubuntu-latest
    name: code format
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: run format
        uses: actions-rs/cargo@v1
        with:
          command: check