name: code check for rust

on:
  push:
    paths:
      - '**/*.rs'

jobs:
  check:
    runs-on: ubuntu-latest
    name: code check
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: run check
        uses: actions-rs/cargo@v1
        with:
          command: check