name: code test

on:
  push:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: test code
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: run test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-fail-fast